// TODO: Include packages needed for this application

// process.argv

const inquirer = require ('inquirer');
const fs = require ('fs');

// TODO: Create an array of questions for user input

const myLicenses = [{
    name: 'apache',
    badgeURL: `[![License](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)`,
    content: `   Copyright 2023 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.`
},{
    name: 'boost',
    badgeURL: `[![License](https://img.shields.io/badge/License-Boost_1.0-lightblue.svg)](https://www.boost.org/LICENSE_1_0.txt)`,
    content: `  Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.`,
},{
    name: 'ISC',
    badgeURL: `[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)](https://opensource.org/licenses/ISC)`,
    content: `  Copyright 2023 

    Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, 
    provided that the above copyright notice and this permission notice appear in all copies.
    
    THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD 
    TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. 
    IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL 
    DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN 
    AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
    WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.`
},{
    name: 'MIT',
    badgeURL: '[![License: ISC](https://img.shields.io/badge/License-ISC-blue.svg)](https://opensource.org/licenses/ISC)',
    content: `  Copyright 2023 

    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
    INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
    PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
    FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
    THE SOFTWARE.`
}
];

inquirer.prompt ([
    {
        name: 'projectTitle',
        message: 'Enter your project title',
        type: 'input'
    }, 
    {
        name: 'description',
        message: 'Enter the description of your project',
        type: 'input'
    }, 
    {
        name: 'installation',
        message: 'Enter installation instructions',
        type: 'input'
    },
    {
        name: 'usage',
        message: 'Enter the usage information',
        type: 'input'
    },
    {
        name: 'contribution',
        message: 'Enter the contribution guidelines',
        type: 'input'
    },
    {
        name: 'test',
        message: 'Enter test instructions',
        type: 'input'
    },
    {
        name: 'license',
        message: 'Which license would you like to use?',
        type: 'list',
        choices: ['apache', 'boost', 'ISC', 'MIT']
    },
    {
        name: 'username',
        message: 'Enter your github username',
        type: 'input'
    },
    {
        name: 'email',
        message: 'Enter your email address',
        type: 'input'
    },
   
   

]).then (answers => {
    fs.writeFile ('README.md', fileGenerator(answers), (err)=>{
        if (err){
            return console.log(err);
        }
        console.log ('Success!');
    })
});

// TODO: Create a function to write README file
const fileGenerator = ({projectTitle, description, installation, usage, contribution, test, license, username, email}) => {
    let licensePos;
    myLicenses.forEach ( (currentV, i)=> {
        if (currentV.name==license) {
            licensePos = i;
        }
    })
    return `# ${projectTitle}       
${myLicenses[licensePos].badgeURL}
## Description
${description}

## Installation
${installation}

## Usage
${usage}

## Contributions
${contribution}

## Tests
${test}

## License
${myLicenses[licensePos].content}

## Questions
If you would like to contact me please email me at ${email}
And my github profile is ![https://github.com/${username}](https://github.com/${username})

## Table of Contents (Optional)

- [Description](##Description)
- [Installation](##Installation)
- [Usage](##Usage)
- [Contributions](##Contributions)
- [License](##License)
- [Questions](##Questions)`;
}

// TODO: Create a function to initialize app
function index_init() {}

// Function call to initialize app
index_init();
